import = [
    "~/.config/alacritty/themes/themes/iris.toml"
]

[font]
size = 12.0

[font.normal]
family = "ProggyClean Nerd Font"

[shell]
args = ["-l", "-c", "tmux && clear"]
program = "/bin/zsh"

[window]
opacity = 1
decorations = "none"

[window.dimensions]
columns = 88
lines = 24

[window.padding]
x = 5
y = 5

[window.position]
x = 1600
y = 800